### ISSUE TITLE
PRIORTIZATION

### ISSUE THREAD

**Issue by sturkistany** [VCCRI/VPOT#3]
Hi 

I am really interested in VPOT to prioritize variants. first I used the example provided (test data) it worked perfectly. 

I have multiple VCF multiple patient samples, VPOT worked with two but not the third one 

1. Could you please help me to figure out why it didn't work with my third vcf file ?   as the error message doesn't specify couldn't upload the vcf

2. when i create test_VCF_sample_list.txt  in Linux VPOT doesn't read the samples and it gives me error ; how can i overcome this issue although im checking the space and the spelling? 
error message : FileNotFoundError: [Errno 2] No such file or directory: 'PBG-653-21_S3.vcf PBG-653-21_S3'
code used: 
[sturkistany@klogin1 project2] i = PBG-653-21_S3.vcf
[sturkistany@klogin1 project2] j=$(echo $i | cut -f1 -d'.')
[sturkistany@klogin1 project2]$ echo -e $i $j > test_VCF_sample_$j.txt
[sturkistany@klogin1 project2]$ sed -i 's/\r$//g' test_VCF_sample_$j.txt
[sturkistany@klogin1 project2]python3 ../../VPOT.py priority testout_ test_VCF_sample_$j.txt default_0.001_variants_parameters_PPF.txt
#VPOT version 2 - 07/01/2021
VPOT Prioritisation - Main
Samples input files :  test_VCF_sample_PBG-653-21_S3.txt
vcf PBG-653-21_S3
VPOT: Parameter file supplied
QC MaxCOverage :  0
QC Hete_balance :  0
QC Genotype_Quality :  0
VS Score Threshold :  0
default_0.001_variants_parameters_PPF.txt
Traceback (most recent call last):
  File "../../VPOT.py", line 177, in <module>
    main()
  File "../../VPOT.py", line 135, in main
    VPOT_1_prioritise.main() #
  File "/fefs1/cegmr/sturkistany/VPOT-master/VPOT_1_prioritise.py", line 299, in main
    error=VPOT_1_1_VCF.read_variant_source_file() #
  File "/fefs1/cegmr/sturkistany/VPOT-master/VPOT_1_1_VCF.py", line 164, in read_variant_source_file
    if ( setup_for_this_src_file(this_line) != 0 ): #
  File "/fefs1/cegmr/sturkistany/VPOT-master/VPOT_1_1_VCF.py", line 268, in setup_for_this_src_file
    with open(file_line[0],'r',encoding="utf-8") as source_vcf : #
FileNotFoundError: [Errno 2] No such file or directory: 'PBG-653-21_S3.vcf PBG-653-21_S3'

3. can i add Clinvar to the PFF parameters ? how ? 

Thanks!

**Comment by croct** [comment]
Thanks for looking at our VPOT software.

When creating your input file for the VPOT priority command, you should separate the values on each line with **tab characters**.  If you look at the example file, `test_data/test_VCF_sample_list.txt`, you will see that the value on each line are separated by tabs (not spaces).  I will update the documentation to make this point clear.

If you wanted to do this with linux bash code, as you showed in your question, you could do this like:
`vcf_f=PBG-653-21_S3.vcf`
`sample=${vcf_f%.vcf}    # extract the filename without the .vcf extension`
`out_f=test_VCF_sample_${sample}.txt`
`echo -e "${vcf_f}\t${sample}" > $out_f`
`# you could add more lines to the file by using something like:`
`# ...similar code as above to`
`# echo -e "${vcf_f_2}\t${sample_2}" >> $out_f`


Of course for testing purposes, you don't need to do this - you could just create your file with your preferred text editor - making sure that actual tab characters are used to separate the vcf filename & the sample name.

_**"can i add Clinvar to the PFF parameters ? how ?"**_
Yes.  Using the VT section of the PPF file.

Refer to `test_data/default_0.001_variants_parameters_PPF.txt`  - the default PPF file.  You could add a line for Clinvar.  E.g.
`VT CLNSIG Pathogenic 200`
This would score an INFO field value of CLNSIG equal to "Pathogenic" a value of 200.
NOTE - **use tabs to separate values** - not spaces.  It will be easier to use a text editor to edit this file.
Also NOTE that the supplied test data files do not have the normal VCF annotation for Clinvar.  Use your own data or modify the supplied test data so that the INFO field in the VCF contains the correct annotation (e.g. ` ...;CLNSIG=Pathogenic;...`)

I hope this helps to move you forward testing VPOT.

**Comment by sturkistany** [comment]
Thanks for answering my questions ! 

regarding the population frequency .. PF I don't want to filter out variants.. instead i want to weight the population frequency according to ranges 
for example : 
ExAC_ALL	 less than and equal to .01  scored 100 
ExAC_ALL	 greater than and equal to .05  scored -100 
ExAC_ALL .011 - .049  scored 0 

is this possible with VPOT?

**Comment by croct** [comment]
You can use any annotation field for prioritisation determination within the PD field.
In the case of ExAC_ALL, you would set it as a numeric PD field with different scoring boundaries, like the CADD_phred PD line you see in the example PPF.
eg : 

`PD<tab>ExAC_ALL<tab>N<tab>0.011<100>0.5<tab>0<tab>0.5<tab>-100`

You do not need to have ExAC_ALL in the PF field, or you can keep it as a bookmark with the value 1.01, so it keeps all variants.

**Comment by croct** [comment]
The example line above should have read:

`PD<tab>ExAC_ALL<tab>N<tab>0.011<100>0.5<tab>0<tab>0.5<tab>-100`

**Comment by sturkistany** [comment]
Thanks it worked with me. 

for me im using Annovar as annotation tool, and whenever ExAC_ALL has no value it is given (.) e.g. ExAC_ALL=.; 

is there a way to weight it without replace the . with value such as -999 ?

**Comment by croct** [comment]
Yes.  

NOTE that a numeric value of "." will be treated as -999 for the PF setting.  You can allow for this in your PF settings in the PPF file.  

If you would like to score the "." value, you could create new PD entry like:
`PD<tab>ExAC_ALL<tab>A<tab>.<tab>100`
This example assigns a VPOT value of 1 to an alpha value of "." for ExAC_ALL.  

You can still have another PD ExAC_ALL entry for your numeric values.
